# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
networks:
- id: 11155420
  start_block: 0
  contracts:
  - name: SharingWishVault
    address:
    - 0x9be5488189d1bBD2E409790252da4Fc627c5d904
    handler: src/EventHandlers.ts
    events:
    - event: EmergencyModeToggled(bool mode)
    - event: FundsClaimed(uint256 indexed vaultId, address indexed claimer, address token, uint256 amount)
    - event: FundsDonated(uint256 indexed vaultId, address indexed donor, address token, uint256 amount)
    - event: FundsWithdrawn(uint256 indexed vaultId, address indexed withdrawer, address token, uint256 amount)
    - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
    - event: VaultCreated(uint256 indexed vaultId, address indexed creator, string message)
    - event: VaultSettled(uint256 indexed vaultId, address indexed claimer, address token, uint256 maxClaimableAmount)
rollback_on_reorg: false
