# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
networks:
- id: 11155420
  start_block: 22920754
  contracts:
  - name: SharingWishVault
    address:
    - 0xd9A321d46470704FF21E35E01793E66101441994
    handler: src/EventHandlers.ts
    events:
    - event: EmergencyModeToggled(bool mode)
    - event: FundsClaimed(uint256 indexed vaultId, address indexed claimer, address token, uint256 amount)
    - event: FundsDonated(uint256 indexed vaultId, address indexed donor, address token, uint256 amount)
    - event: FundsWithdrawn(uint256 indexed vaultId, address indexed withdrawer, address token, uint256 amount)
    - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
    - event: VaultCreated(uint256 indexed vaultId, address indexed creator, address token, uint256 lockTime, string message)
    - event: VaultSettled(uint256 indexed vaultId, address indexed claimer, address token, uint256 maxClaimableAmount, bool autoClaim)
field_selection:
  transaction_fields:
  - "hash"
  - "transactionIndex"
  - "gasUsed"
  - "from"
  - "to"
  - "gas"
  block_fields:
  - "parentHash"
rollback_on_reorg: false
